version: '3.8'

services:
  monitored-server:
    image: ubuntu:22.04
    container_name: monitored-server
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y wget &&
      wget https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz &&
      tar xvfz node_exporter-1.6.1.linux-amd64.tar.gz &&
      cd node_exporter-1.6.1.linux-amd64 &&
      ./node_exporter"
    networks:
      - monitor-net
    ports:
      - "9100:9100"  # Porta do Node Exporter
    volumes:
      - /proc:/host/proc:ro  # Para permitir que o Node Exporter acesse as métricas do sistema

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # Porta do Prometheus
    networks:
      - monitor-net
      #Link do Data Souce http://prometheus:9090


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Porta do Grafana
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
